// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderPlacer.SamsClub.Models;
//
//    var bjsSearchProductQueryDto = BjsSearchProductQueryDto.FromJson(jsonString);

namespace OrderPlacer.Bjs.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BjsSearchProductQueryDto
    {
        [JsonProperty("pageSize", NullValueHandling = NullValueHandling.Ignore)]
        public long? PageSize { get; set; }

        [JsonProperty("area", NullValueHandling = NullValueHandling.Ignore)]
        public string Area { get; set; }

        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Fields { get; set; }

        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
    
        public string Query { get; set; }

        [JsonProperty("collection", NullValueHandling = NullValueHandling.Ignore)]
        public string Collection { get; set; }

        [JsonProperty("skip", NullValueHandling = NullValueHandling.Ignore)]
        public long? Skip { get; set; }
    }

    public partial class BjsSearchProductQueryDto
    {
        public static BjsSearchProductQueryDto FromJson(string json) => JsonConvert.DeserializeObject<BjsSearchProductQueryDto>(json, Converter.Settings);
    }


}
