// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderPlacer.SamsClub.Models;
//
//    var bjsSearchProductResponseDto = BjsSearchProductResponseDto.FromJson(jsonString);

namespace OrderPlacer.Bjs.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class BjsSearchProductResponseDto
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("area", NullValueHandling = NullValueHandling.Ignore)]
        public string Area { get; set; }

        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? Query { get; set; }

        [JsonProperty("records", NullValueHandling = NullValueHandling.Ignore)]
        public List<Record> Records { get; set; }

        [JsonProperty("totalRecordCount", NullValueHandling = NullValueHandling.Ignore)]
        public long? TotalRecordCount { get; set; }

        [JsonProperty("biasingProfile", NullValueHandling = NullValueHandling.Ignore)]
        public string BiasingProfile { get; set; }

        [JsonProperty("originalQuery", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? OriginalQuery { get; set; }

        [JsonProperty("template", NullValueHandling = NullValueHandling.Ignore)]
        public Template Template { get; set; }

        [JsonProperty("pageInfo", NullValueHandling = NullValueHandling.Ignore)]
        public PageInfo PageInfo { get; set; }

        [JsonProperty("matchStrategy", NullValueHandling = NullValueHandling.Ignore)]
        public MatchStrategy MatchStrategy { get; set; }

        [JsonProperty("availableNavigation", NullValueHandling = NullValueHandling.Ignore)]
        public List<AvailableNavigation> AvailableNavigation { get; set; }

        [JsonProperty("selectedNavigation", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> SelectedNavigation { get; set; }

        [JsonProperty("didYouMean", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> DidYouMean { get; set; }

        [JsonProperty("siteParams", NullValueHandling = NullValueHandling.Ignore)]
        public List<SiteParam> SiteParams { get; set; }

        [JsonProperty("originalRequest", NullValueHandling = NullValueHandling.Ignore)]
        public OriginalRequest OriginalRequest { get; set; }

        [JsonProperty("relatedQueries", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> RelatedQueries { get; set; }

        [JsonProperty("rewrites", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Rewrites { get; set; }

        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
        public Metadata Metadata { get; set; }

        [JsonProperty("empty", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Empty { get; set; }
    }

    public partial class AvailableNavigation
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("displayName", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayName { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("refinements", NullValueHandling = NullValueHandling.Ignore)]
        public List<Refinement> Refinements { get; set; }

        [JsonProperty("metadata", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> Metadata { get; set; }

        [JsonProperty("range", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Range { get; set; }

        [JsonProperty("or", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Or { get; set; }

        [JsonProperty("moreRefinements", NullValueHandling = NullValueHandling.Ignore)]
        public bool? MoreRefinements { get; set; }
    }

    public partial class Refinement
    {
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
        public long? Count { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        public string Value { get; set; }

        [JsonProperty("high", NullValueHandling = NullValueHandling.Ignore)]
        public string High { get; set; }

        [JsonProperty("low", NullValueHandling = NullValueHandling.Ignore)]
        public string Low { get; set; }
    }

    public partial class MatchStrategy
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("rules", NullValueHandling = NullValueHandling.Ignore)]
        public List<Rule> Rules { get; set; }
    }

    public partial class Rule
    {
        [JsonProperty("terms", NullValueHandling = NullValueHandling.Ignore)]
        public long? Terms { get; set; }

        [JsonProperty("mustMatch", NullValueHandling = NullValueHandling.Ignore)]
        public long? MustMatch { get; set; }

        [JsonProperty("percentage", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Percentage { get; set; }

        [JsonProperty("termsGreaterThan", NullValueHandling = NullValueHandling.Ignore)]
        public long? TermsGreaterThan { get; set; }
    }

    public partial class Metadata
    {
        [JsonProperty("cached", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Cached { get; set; }

        [JsonProperty("recordLimitReached", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RecordLimitReached { get; set; }

        [JsonProperty("totalTime", NullValueHandling = NullValueHandling.Ignore)]
        public long? TotalTime { get; set; }
    }

    public partial class OriginalRequest
    {
        [JsonProperty("collection", NullValueHandling = NullValueHandling.Ignore)]
        public string Collection { get; set; }

        [JsonProperty("area", NullValueHandling = NullValueHandling.Ignore)]
        public string Area { get; set; }

        [JsonProperty("query", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? Query { get; set; }

        [JsonProperty("skip", NullValueHandling = NullValueHandling.Ignore)]
        public long? Skip { get; set; }

        [JsonProperty("pageSize", NullValueHandling = NullValueHandling.Ignore)]
        public long? PageSize { get; set; }

        [JsonProperty("fields", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Fields { get; set; }

        [JsonProperty("pruneRefinements", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PruneRefinements { get; set; }
    }

    public partial class PageInfo
    {
        [JsonProperty("recordStart", NullValueHandling = NullValueHandling.Ignore)]
        public long? RecordStart { get; set; }

        [JsonProperty("recordEnd", NullValueHandling = NullValueHandling.Ignore)]
        public long? RecordEnd { get; set; }
    }

    public partial class Record
    {
        [JsonProperty("collection", NullValueHandling = NullValueHandling.Ignore)]
        public string Collection { get; set; }

        [JsonProperty("allMeta", NullValueHandling = NullValueHandling.Ignore)]
        public AllMeta AllMeta { get; set; }

        [JsonProperty("_id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("_u", NullValueHandling = NullValueHandling.Ignore)]
        public Uri U { get; set; }

        [JsonProperty("_t", NullValueHandling = NullValueHandling.Ignore)]
        public string T { get; set; }
    }

    public partial class AllMeta
    {
        [JsonProperty("gbi_Has_Variants", NullValueHandling = NullValueHandling.Ignore)]
        public string GbiHasVariants { get; set; }

        [JsonProperty("visualVariant", NullValueHandling = NullValueHandling.Ignore)]
        public List<VisualVariant> VisualVariant { get; set; }



        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? Id { get; set; }

        [JsonProperty("_groupbyinc", NullValueHandling = NullValueHandling.Ignore)]
        public Groupbyinc Groupbyinc { get; set; }

        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }
    }

    public partial class Groupbyinc
    {
        [JsonProperty("productConversion", NullValueHandling = NullValueHandling.Ignore)]
        public long? ProductConversion { get; set; }
    }

    public partial class VisualVariant
    {
        [JsonProperty("gbi_product_tiny_image_url", NullValueHandling = NullValueHandling.Ignore)]
        public string GbiProductTinyImageUrl { get; set; }

        [JsonProperty("nonvisualVariant", NullValueHandling = NullValueHandling.Ignore)]
        public List<NonvisualVariant> NonvisualVariant { get; set; }

        [JsonProperty("product_tiny_image_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ProductTinyImageUrl { get; set; }

        [JsonProperty("pdplink", NullValueHandling = NullValueHandling.Ignore)]
        public string Pdplink { get; set; }
    }

    public partial class NonvisualVariant
    {
        [JsonProperty("new_arrival", NullValueHandling = NullValueHandling.Ignore)]
        public string NewArrival { get; set; }

        [JsonProperty("product_url", NullValueHandling = NullValueHandling.Ignore)]
        public string ProductUrl { get; set; }

        [JsonProperty("gbi_attributes", NullValueHandling = NullValueHandling.Ignore)]
        public List<GbiAttribute> GbiAttributes { get; set; }

        [JsonProperty("gbi_showpricecartpostlogin", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiShowpricecartpostlogin { get; set; }

        [JsonProperty("product_price", NullValueHandling = NullValueHandling.Ignore)]
        public string ProductPrice { get; set; }

        [JsonProperty("availability", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> Availability { get; set; }

        [JsonProperty("gbi_is_reserveable", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiIsReserveable { get; set; }

        [JsonProperty("gbi_shipping_is_included", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiShippingIsIncluded { get; set; }

        [JsonProperty("gbi_ship_from_club", NullValueHandling = NullValueHandling.Ignore)]
        public string GbiShipFromClub { get; set; }

        [JsonProperty("num_comments", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? NumComments { get; set; }

        [JsonProperty("listprice", NullValueHandling = NullValueHandling.Ignore)]
        public string Listprice { get; set; }

        [JsonProperty("gbi_has_instantSavings", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiHasInstantSavings { get; set; }

        [JsonProperty("displayPrice", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayPrice { get; set; }

        [JsonProperty("club", NullValueHandling = NullValueHandling.Ignore)]
        public List<Club> Club { get; set; }

        [JsonProperty("item_partnumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(DecodeArrayConverter))]
        public List<long> ItemPartnumber { get; set; }

        [JsonProperty("gbi_availability", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> GbiAvailability { get; set; }

        [JsonProperty("weighted", NullValueHandling = NullValueHandling.Ignore)]
        public string Weighted { get; set; }

        [JsonProperty("gbi_club_price_is_visible", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiClubPriceIsVisible { get; set; }

        [JsonProperty("clubid_price", NullValueHandling = NullValueHandling.Ignore)]
        public string ClubidPrice { get; set; }

        [JsonProperty("gbi_special_offers", NullValueHandling = NullValueHandling.Ignore)]
        public List<object> GbiSpecialOffers { get; set; }

        [JsonProperty("gbi_coupon_is_available", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiCouponIsAvailable { get; set; }

        [JsonProperty("gbi_is_same_day_delivery", NullValueHandling = NullValueHandling.Ignore)]
        public string GbiIsSameDayDelivery { get; set; }

        [JsonProperty("average_rating", NullValueHandling = NullValueHandling.Ignore)]
        public string AverageRating { get; set; }

        [JsonProperty("item_name", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemName { get; set; }

        [JsonProperty("maxMapPrice", NullValueHandling = NullValueHandling.Ignore)]
        public string MaxMapPrice { get; set; }

        [JsonProperty("mapprice", NullValueHandling = NullValueHandling.Ignore)]
        public string Mapprice { get; set; }

        [JsonProperty("item_image", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemImage { get; set; }

        [JsonProperty("gbi_toprated", NullValueHandling = NullValueHandling.Ignore)]
        
        public long? GbiToprated { get; set; }

        [JsonProperty("partnumber", NullValueHandling = NullValueHandling.Ignore)]
        public string Partnumber { get; set; }
    }

    public partial class Club
    {
        [JsonProperty("clipless_coupon", NullValueHandling = NullValueHandling.Ignore)]
        public string CliplessCoupon { get; set; }

        [JsonProperty("price", NullValueHandling = NullValueHandling.Ignore)]
        public string Price { get; set; }

        [JsonProperty("coupon_price", NullValueHandling = NullValueHandling.Ignore)]
        public string CouponPrice { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("list_price", NullValueHandling = NullValueHandling.Ignore)]
        public string ListPrice { get; set; }

        [JsonProperty("coupon_enddate", NullValueHandling = NullValueHandling.Ignore)]
        public string CouponEnddate { get; set; }
    }

    public partial class GbiAttribute
    {
        [JsonProperty("Fsa_eligible", NullValueHandling = NullValueHandling.Ignore)]
        public string FsaEligible { get; set; }
    }

    public partial class SiteParam
    {
        [JsonProperty("key", NullValueHandling = NullValueHandling.Ignore)]
        public string Key { get; set; }

        [JsonProperty("value", NullValueHandling = NullValueHandling.Ignore)]
        
        public bool? Value { get; set; }
    }

    public partial class Template
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("zones", NullValueHandling = NullValueHandling.Ignore)]
        public Zones Zones { get; set; }
    }

    public partial class Zones
    {
    }

    public partial struct GbiCategor
    {
        public List<object> AnythingArray;
        public string String;

        public static implicit operator GbiCategor(List<object> AnythingArray) => new GbiCategor { AnythingArray = AnythingArray };
        public static implicit operator GbiCategor(string String) => new GbiCategor { String = String };
    }

    public partial class BjsSearchProductResponseDto
    {
        public static BjsSearchProductResponseDto FromJson(string json) => JsonConvert.DeserializeObject<BjsSearchProductResponseDto>(json, Converter.Settings);
    }





    
}
