// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderPlacer.SamsClub.Models;
//
//    var samsErrorDto = SamsErrorDto.FromJson(jsonString);

namespace OrderPlacer.SamsClub.Models
{
    using Newtonsoft.Json;
    using System.Collections.Generic;

    public partial class SamsErrorDto
    {
        [JsonProperty("errors", NullValueHandling = NullValueHandling.Ignore)]
        public List<Error> Errors { get; set; }
    }

    public partial class Error
    {
        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        [JsonProperty("message", NullValueHandling = NullValueHandling.Ignore)]
        public string Message { get; set; }

        [JsonProperty("displayMessage", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayMessage { get; set; }
    }

    public partial class SamsErrorDto
    {
        public static SamsErrorDto FromJson(string json) => JsonConvert.DeserializeObject<SamsErrorDto>(json, Converter.Settings);
    }


}
