using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderPlacer.SamsClub.Models;
//
//    var samsMemberShipInfoDto = SamsMemberShipInfoDto.FromJson(jsonString);

namespace OrderPlacer.SamsClub.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class SamsMemberShipInfoDto
    {
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        [JsonProperty("payload", NullValueHandling = NullValueHandling.Ignore)]
        public Payload Payload { get; set; }
    }

    public partial class Payload
    {
        [JsonProperty("membership", NullValueHandling = NullValueHandling.Ignore)]
        public Membership Membership { get; set; }

        [JsonProperty("member", NullValueHandling = NullValueHandling.Ignore)]
        public List<Member> Member { get; set; }

        [JsonProperty("subscribedToPreferenceCenter", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SubscribedToPreferenceCenter { get; set; }
    }

    public partial class Member
    {
        [JsonProperty("memberName", NullValueHandling = NullValueHandling.Ignore)]
        public Name MemberName { get; set; }

        [JsonProperty("hasOptOutEnabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasOptOutEnabled { get; set; }

        [JsonProperty("fullMembershipId", NullValueHandling = NullValueHandling.Ignore)]
        public string FullMembershipId { get; set; }

        [JsonProperty("memberId", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? MemberId { get; set; }

        [JsonProperty("cardType", NullValueHandling = NullValueHandling.Ignore)]
        public string CardType { get; set; }

        [JsonProperty("membershipId", NullValueHandling = NullValueHandling.Ignore)]
        public string MembershipId { get; set; }

        [JsonProperty("cardStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string CardStatus { get; set; }

        [JsonProperty("homePhone", NullValueHandling = NullValueHandling.Ignore)]
        public HomePhone HomePhone { get; set; }

        [JsonProperty("consentToContactViaHomePhone", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ConsentToContactViaHomePhone { get; set; }

        [JsonProperty("homeEmail", NullValueHandling = NullValueHandling.Ignore)]
        public string HomeEmail { get; set; }

        [JsonProperty("consentToContactViaHomeEmail", NullValueHandling = NullValueHandling.Ignore)]
        public bool? ConsentToContactViaHomeEmail { get; set; }

        [JsonProperty("hasOnlineProfile", NullValueHandling = NullValueHandling.Ignore)]
        public bool? HasOnlineProfile { get; set; }

        [JsonProperty("onlineProfile", NullValueHandling = NullValueHandling.Ignore)]
        public OnlineProfile OnlineProfile { get; set; }
    }

    public partial class HomePhone
    {
        [JsonProperty("completeNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string CompleteNumber { get; set; }
    }

    public partial class Name
    {
        [JsonProperty("firstName", NullValueHandling = NullValueHandling.Ignore)]
        public string FirstName { get; set; }

        [JsonProperty("lastName", NullValueHandling = NullValueHandling.Ignore)]
        public string LastName { get; set; }

        [JsonProperty("fullName", NullValueHandling = NullValueHandling.Ignore)]
        public string FullName { get; set; }
    }

    public partial class OnlineProfile
    {
        [JsonProperty("loginEmail", NullValueHandling = NullValueHandling.Ignore)]
        public string LoginEmail { get; set; }

        [JsonProperty("legacyProfileId", NullValueHandling = NullValueHandling.Ignore)]
        public string LegacyProfileId { get; set; }
    }

    public partial class Membership
    {
        [JsonProperty("membershipId", NullValueHandling = NullValueHandling.Ignore)]
        public string MembershipId { get; set; }

        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        [JsonProperty("personId", NullValueHandling = NullValueHandling.Ignore)]
        public string PersonId { get; set; }

        [JsonProperty("membershipType", NullValueHandling = NullValueHandling.Ignore)]
        public string MembershipType { get; set; }

        [JsonProperty("cardType", NullValueHandling = NullValueHandling.Ignore)]
        public string CardType { get; set; }

        [JsonProperty("issuingClubId", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? IssuingClubId { get; set; }

        [JsonProperty("preferredClub", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? PreferredClub { get; set; }

        [JsonProperty("startDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? StartDate { get; set; }

        [JsonProperty("nextRenewDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? NextRenewDate { get; set; }

        [JsonProperty("benefitsStartDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? BenefitsStartDate { get; set; }

        [JsonProperty("membershipSince", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? MembershipSince { get; set; }

        [JsonProperty("currentStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string CurrentStatus { get; set; }

        [JsonProperty("autoRenew", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AutoRenew { get; set; }

        [JsonProperty("isTaxExempt", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsTaxExempt { get; set; }

        [JsonProperty("isEasyConverted", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsEasyConverted { get; set; }

        [JsonProperty("parentMembershipDetails", NullValueHandling = NullValueHandling.Ignore)]
        public ParentMembershipDetails ParentMembershipDetails { get; set; }

        [JsonProperty("paidStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string PaidStatus { get; set; }

        [JsonProperty("plusStatus", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PlusStatus { get; set; }

        [JsonProperty("autoBill", NullValueHandling = NullValueHandling.Ignore)]
        public bool? AutoBill { get; set; }

        [JsonProperty("payrollDeduction", NullValueHandling = NullValueHandling.Ignore)]
        public bool? PayrollDeduction { get; set; }

        [JsonProperty("taxStatCode", NullValueHandling = NullValueHandling.Ignore)]
        public bool? TaxStatCode { get; set; }

        [JsonProperty("enableFreeShippingForPlus", NullValueHandling = NullValueHandling.Ignore)]
        public bool? EnableFreeShippingForPlus { get; set; }

        [JsonProperty("daysTillExpiry", NullValueHandling = NullValueHandling.Ignore)]
        public long? DaysTillExpiry { get; set; }

        [JsonProperty("organizationName", NullValueHandling = NullValueHandling.Ignore)]
        public OrganizationName OrganizationName { get; set; }

        [JsonProperty("physicalAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Address PhysicalAddress { get; set; }

        [JsonProperty("mailingAddress", NullValueHandling = NullValueHandling.Ignore)]
        public Address MailingAddress { get; set; }

        [JsonProperty("marketingContactName", NullValueHandling = NullValueHandling.Ignore)]
        public Name MarketingContactName { get; set; }

        [JsonProperty("businessType", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? BusinessType { get; set; }

        [JsonProperty("sicCode", NullValueHandling = NullValueHandling.Ignore)]
        public SicCode SicCode { get; set; }

        [JsonProperty("businessPhone", NullValueHandling = NullValueHandling.Ignore)]
        public string BusinessPhone { get; set; }

        [JsonProperty("encryptedMembershipNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string EncryptedMembershipNumber { get; set; }

        [JsonProperty("bvUserToken", NullValueHandling = NullValueHandling.Ignore)]
        public string BvUserToken { get; set; }

        [JsonProperty("upgradeInfo", NullValueHandling = NullValueHandling.Ignore)]
        public Info UpgradeInfo { get; set; }

        [JsonProperty("renewalInfo", NullValueHandling = NullValueHandling.Ignore)]
        public RenewalInfo RenewalInfo { get; set; }

        [JsonProperty("convertInfo", NullValueHandling = NullValueHandling.Ignore)]
        public ConvertInfo ConvertInfo { get; set; }

        [JsonProperty("newInfo", NullValueHandling = NullValueHandling.Ignore)]
        public Info NewInfo { get; set; }
    }

    public partial class ConvertInfo
    {
        [JsonProperty("CONVERT", NullValueHandling = NullValueHandling.Ignore)]
        public List<Convert> Convert { get; set; }
    }

    public partial class Convert
    {
        [JsonProperty("itemNumber", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? ItemNumber { get; set; }

        [JsonProperty("upcNumber", NullValueHandling = NullValueHandling.Ignore)]
        public string UpcNumber { get; set; }

        [JsonProperty("itemShortDescription", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemShortDescription { get; set; }

        [JsonProperty("itemLongDescription", NullValueHandling = NullValueHandling.Ignore)]
        public string ItemLongDescription { get; set; }

        [JsonProperty("itemPrice", NullValueHandling = NullValueHandling.Ignore)]
        public long? ItemPrice { get; set; }

        [JsonProperty("itemTaxAmount", NullValueHandling = NullValueHandling.Ignore)]
        public long? ItemTaxAmount { get; set; }

        [JsonProperty("productInfo", NullValueHandling = NullValueHandling.Ignore)]
        public ProductInfo ProductInfo { get; set; }
    }



 

    

    public partial class OrganizationName
    {
        [JsonProperty("primaryName", NullValueHandling = NullValueHandling.Ignore)]
        public string PrimaryName { get; set; }
    }

    public partial class ParentMembershipDetails
    {
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? Id { get; set; }

        [JsonProperty("role", NullValueHandling = NullValueHandling.Ignore)]
        public string Role { get; set; }

        [JsonProperty("personId", NullValueHandling = NullValueHandling.Ignore)]
        public Guid? PersonId { get; set; }

        [JsonProperty("membershipAccount", NullValueHandling = NullValueHandling.Ignore)]
        public string MembershipAccount { get; set; }

        [JsonProperty("paidStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string PaidStatus { get; set; }

        [JsonProperty("memberStatus", NullValueHandling = NullValueHandling.Ignore)]
        public string MemberStatus { get; set; }

        [JsonProperty("endDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? EndDate { get; set; }
    }

    public partial class RenewalInfo
    {
        [JsonProperty("renewalStatus", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RenewalStatus { get; set; }

        [JsonProperty("isMembershipExpired", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsMembershipExpired { get; set; }

        [JsonProperty("isAutoRenew", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsAutoRenew { get; set; }

        [JsonProperty("expiryDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTimeOffset? ExpiryDate { get; set; }
    }

    public partial class SicCode
    {
        [JsonProperty("baseCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? BaseCode { get; set; }

        [JsonProperty("businessLineDesc", NullValueHandling = NullValueHandling.Ignore)]
        public string BusinessLineDesc { get; set; }

        [JsonProperty("purposeCode", NullValueHandling = NullValueHandling.Ignore)]
        [JsonConverter(typeof(ParseStringConverter))]
        public long? PurposeCode { get; set; }

        [JsonProperty("subIndustryCode", NullValueHandling = NullValueHandling.Ignore)]
        public string SubIndustryCode { get; set; }
    }

    


   
}
