using System;
namespace ShipStationApi.Models
{
    // <auto-generated />
    //
    // To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
    //
    //    using OrderPlacer.Bjs.Models;
    //
    //    var samsTrackingInfoDto = SamsTrackingInfoDto.FromJson(jsonString);

    
        using System;
        using System.Collections.Generic;

        using System.Globalization;
        using Newtonsoft.Json;
        using Newtonsoft.Json.Converters;

        public partial class ShipStationCarriersInfoDto
        {
            [JsonProperty("providerId", NullValueHandling = NullValueHandling.Ignore)]
            public long? ProviderId { get; set; }

            [JsonProperty("carrierId", NullValueHandling = NullValueHandling.Ignore)]
            public long? CarrierId { get; set; }

            [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
            public string Name { get; set; }

            [JsonProperty("apiCode", NullValueHandling = NullValueHandling.Ignore)]
            public string ApiCode { get; set; }

            [JsonProperty("logoUrl")]
            public Uri LogoUrl { get; set; }

            [JsonProperty("iconUrl")]
            public Uri IconUrl { get; set; }

            [JsonProperty("description")]
            public string Description { get; set; }

            [JsonProperty("beta", NullValueHandling = NullValueHandling.Ignore)]
            public bool? Beta { get; set; }

            [JsonProperty("searchTerms")]
            public List<string> SearchTerms { get; set; }

            [JsonProperty("active", NullValueHandling = NullValueHandling.Ignore)]
            public bool? Active { get; set; }

            [JsonProperty("bringYourOwnLabelCapable", NullValueHandling = NullValueHandling.Ignore)]
            public bool? BringYourOwnLabelCapable { get; set; }
        }

        

       
        
    }


