using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ShipStationApi.Models;
//
//    var shipStationRateInfoDto = ShipStationRateInfoDto.FromJson(jsonString);

namespace ShipStationApi.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ShipStationRateInfoDto
    {
        public string PackageName { get; set; }
        public string CarrierName { get; set; }
        [JsonProperty("serviceName", NullValueHandling = NullValueHandling.Ignore)]
        public string ServiceName { get; set; }

        [JsonProperty("serviceCode", NullValueHandling = NullValueHandling.Ignore)]
        public string ServiceCode { get; set; }

        [JsonProperty("shipmentCost", NullValueHandling = NullValueHandling.Ignore)]
        public double? ShipmentCost { get; set; }

        [JsonProperty("otherCost", NullValueHandling = NullValueHandling.Ignore)]
        public double? OtherCost { get; set; }
    }

    public partial class ShipStationRateInfoDto
    {
        public static List<ShipStationRateInfoDto> FromJson(string json) => JsonConvert.DeserializeObject<List<ShipStationRateInfoDto>>(json, Converter.Settings);
    }

   

   
}
