// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using OrderPlacer.Bjs.Models;
//
//    var shipCarriersDto = ShipCarriersDto.FromJson(jsonString);

namespace ShipStationApi.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ShipCarriersDto
    {
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        [JsonProperty("accountNumber")]
        public string AccountNumber { get; set; }

        [JsonProperty("requiresFundedAccount", NullValueHandling = NullValueHandling.Ignore)]
        public bool? RequiresFundedAccount { get; set; }

        [JsonProperty("balance", NullValueHandling = NullValueHandling.Ignore)]
        public double? Balance { get; set; }

        [JsonProperty("nickname")]
        public string Nickname { get; set; }

        [JsonProperty("shippingProviderId", NullValueHandling = NullValueHandling.Ignore)]
        public long? ShippingProviderId { get; set; }

        [JsonProperty("primary", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Primary { get; set; }
    }

    public partial class ShipCarriersDto
    {
        public static List<ShipCarriersDto> FromJson(string json) => JsonConvert.DeserializeObject<List<ShipCarriersDto>>(json, Converter.Settings);
    }


}
