using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ShipStationApi.Models;
//
//    var shipStationRateInquiryDto = ShipStationRateInquiryDto.FromJson(jsonString);

namespace ShipStationApi.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ShipStationRateInquiryDto
    {
        [JsonProperty("carrierCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CarrierCode { get; set; }

        [JsonProperty("serviceCode")]
        public object ServiceCode { get; set; }

        [JsonProperty("packageCode")]
        public object PackageCode { get; set; }

        [JsonProperty("fromPostalCode", NullValueHandling = NullValueHandling.Ignore)]
        public string FromPostalCode { get; set; }

        [JsonProperty("toState", NullValueHandling = NullValueHandling.Ignore)]
        public string ToState { get; set; }

        [JsonProperty("toCountry", NullValueHandling = NullValueHandling.Ignore)]
        public string ToCountry { get; set; }

        [JsonProperty("toPostalCode", NullValueHandling = NullValueHandling.Ignore)]
        public string ToPostalCode { get; set; }

        [JsonProperty("toCity", NullValueHandling = NullValueHandling.Ignore)]
        public string ToCity { get; set; }

        [JsonProperty("weight", NullValueHandling = NullValueHandling.Ignore)]
        public Weight Weight { get; set; }

        [JsonProperty("dimensions", NullValueHandling = NullValueHandling.Ignore)]
        public Dimensions Dimensions { get; set; }

        [JsonProperty("confirmation", NullValueHandling = NullValueHandling.Ignore)]
        public string Confirmation { get; set; }

        [JsonProperty("residential", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Residential { get; set; }
    }

   

    

    public partial class ShipStationRateInquiryDto
    {
        public static ShipStationRateInquiryDto FromJson(string json) => JsonConvert.DeserializeObject<ShipStationRateInquiryDto>(json, Converter.Settings);
    }

  

   
}
