using System;
using System.Collections.Generic;
using System.Text;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ShipStationApi.Models;
//
//    var shipStationCarrierServiceInfoDto = ShipStationCarrierServiceInfoDto.FromJson(jsonString);

namespace ShipStationApi.Models
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ShipStationCarrierServiceInfoDto
    {
        [JsonProperty("carrierCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CarrierCode { get; set; }

        [JsonProperty("code", NullValueHandling = NullValueHandling.Ignore)]
        public string Code { get; set; }

        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        [JsonProperty("domestic", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Domestic { get; set; }

        [JsonProperty("international", NullValueHandling = NullValueHandling.Ignore)]
        public bool? International { get; set; }
    }

    public partial class ShipStationCarrierServiceInfoDto
    {
        public static List<ShipStationCarrierServiceInfoDto> FromJson(string json) => JsonConvert.DeserializeObject<List<ShipStationCarrierServiceInfoDto>>(json, Converter.Settings);
    }

  
}
